name: auth
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.3.3
  flutter: 
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true

